using UnityEngine;
using UnityEngine.UI;

public class UIManager : MonoBehaviour
{
    public static UIManager Instance { get; private set; }
    public Canvas MainCanvas { get; private set; }

    [Header("UI Panels")]
    public GameObject inventoryPanel; // Bạn sẽ tạo một Panel trong Canvas và gán vào đây

    private void Awake()
    {
        // 1. Cài đặt Singleton
        if (Instance != null && Instance != this)
        {
            Destroy(this.gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(this.gameObject);

        SetupCanvas();
    }

    private void SetupCanvas()
    {
        // ĐÃ SỬA: Dùng FindAnyObjectByType thay cho FindObjectOfType
        MainCanvas = Object.FindAnyObjectByType<Canvas>();

        if (MainCanvas == null)
        {
            GameObject canvasGO = new GameObject("AutoGeneratedCanvas");
            MainCanvas = canvasGO.AddComponent<Canvas>();
            MainCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGO.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            canvasGO.AddComponent<GraphicRaycaster>();
        }
    }

    private void Update()
    {
        // 2. Bắt sự kiện nhấn phím (Tab hoặc I)
        if (Input.GetKeyDown(KeyCode.Tab) || Input.GetKeyDown(KeyCode.I))
        {
            ToggleInventory();
        }
    }

    public void ToggleInventory()
    {
        if (inventoryPanel != null)
        {
            // Kiểm tra trạng thái hiện tại (đang bật hay tắt)
            bool isOpen = inventoryPanel.activeSelf;

            // Lật ngược trạng thái (đang bật thì tắt, đang tắt thì bật)
            inventoryPanel.SetActive(!isOpen);

            /* * LƯU Ý PHONG CÁCH HARDCORE (Giống Zomboid):
             * Ở Project Zomboid, mở túi đồ lên thời gian VẪN TRÔI, bạn vẫn có thể bị cắn.
             * Nếu bạn muốn game dễ hơn (mở túi là dừng game), hãy bỏ comment dòng code bên dưới:
             */
            // Time.timeScale = isOpen ? 1f : 0f; 
        }
        else
        {
            Debug.LogWarning("Chưa gán Inventory Panel vào UIManager!");
        }
    }
}